from typing import TypedDict, Annotated, Sequence, Optional
from langchain_core.messages import BaseMessage
import operator

class GraphState(TypedDict):
    # ==========================================
    # GLOBAL CONTEXT (Immutable during run)
    # ==========================================
    user_contract: str
    contract_name: str
    readme_specs: str
    
    # ==========================================
    # AGENTIC MEMORY & ROUTING (Dynamic)
    # ==========================================
    # Keeps the running history of what agents have said to each other
    messages: Annotated[Sequence[BaseMessage], operator.add]
    
    # Dictates graph control flow: 'bug_hunter', 'specifier', 'gatekeeper', 'fixer', or 'FINISH'
    next_agent: str  
    
    # What function the system is actively analyzing right now
    current_focus_function: Optional[str]
    
    # The Supervisor's feedback to a sub-agent when it catches a hallucination
    supervisor_critique: Optional[str]  
    
    # ==========================================
    # EXECUTION STATE (Data passed between tools)
    # ==========================================
    mode: str
    intent: str
    queries: list[str]

    # Isolated XML analysis packet injected by process_function() (C1 fix:
    # must be declared or LangGraph silently drops it from the initial state)
    isolated_xml_packet: Optional[str]

    # Set by bug_hunter_node when the Isolator response could not be parsed
    # at all (prevents malformed LLM output from being reported as "safe")
    hunter_parse_error: Optional[str]

    # Raw findings proposed by the Isolator (unverified).
    # NOTE: findings[0] is the finding currently under verification; nodes
    # consume it by returning findings[1:] once resolved.
    findings: list[dict]
    
    # Final, proven bugs that actually passed the Gatekeeper/Z3
    verified_bugs: list[dict]  
    
    # ==========================================
    # ARTIFACTS
    # ==========================================
    z3_code: str
    z3_result: Optional[dict]
    slither_result: Optional[dict]
    bug_report: Optional[str]
    
    # ==========================================
    # SAFETY COUNTERS
    # ==========================================
    # Prevents infinite CEGIS or Supervisor hallucination loops
    iterations: int
    
    # Number of times the Supervisor node has run (bounds hunter/specifier loops)
    supervisor_runs: int
    
    # Number of times the Executor node has run (bounds the Z3-fix loop)
    executor_runs: int

    # Bounded retries when the Isolator response is unparseable (previously a
    # parse failure dead-ended the function's audit with zero recovery)
    hunter_retries: int

    # Set by bug_hunter_node when ALL passes returned empty provider
    # responses (EmptyResponseError or empty-after-think-strip). Signals
    # the router to short-circuit outer retries — retrying on quota or
    # rate-limit exhaustion only burns API credits without producing output.
    hunter_provider_empty: Optional[bool]
    
    # RAG retrieval diagnostics (scores + P@K) captured by the specifier node
    rag_diagnostics: Optional[dict]

    # Phase 2: deterministic semantic model generated by domain/semantics.py
    # (harness dict with 'code'/'quality'; None -> legacy LLM-only encoding)
    semantic_harness: Optional[dict]
    model_quality: Optional[str]

    # Vacuity detection: set by executor_node when Z3 returns UNSAT but the
    # harness model is itself unsatisfiable (guards contradict bounds, or
    # transitions contradict guards). A vacuous UNSAT means nothing was proven.
    vacuity_status: Optional[str]
    vacuity_reason: Optional[str]
    
    
    poc_test_code : str
    forge_output : str
    qc_status : str

    # Wrap probe: BitVec-256 overflow/underflow reachability signals
    # from domain.wrap_probe. None when unavailable or no wrappable writes.
    wrap_probe_signals: Optional[list]

    # Dual-CFG injection: paired function's CFG slice for cross-function
    # reasoning when a compositional pair is flagged (Gap 2).
    compositional_paired_cfg: Optional[str]

    # Multi-call chain harness: Z3 model for writer->reader sequences
    # (Gap 3). None when no high-risk compositional pair exists.
    compositional_harness: Optional[dict]
    compositional_model_quality: Optional[str]